name: tic_tac_toe
description: ""
version: 1.0.0

environment:
  sdk: '>=3.3.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  shared_preferences: ^2.2.3
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
flutter:
  uses-material-design: true

  fonts:
    - family: 'OpenSans'
      fonts:
        - asset: assets/fonts/open_sans.ttf
        - asset: assets/fonts/open_sans_italic.ttf
